"""Init migration

Revision ID: 9e65fe66c865
Revises: 
Create Date: 2020-06-15 21:26:56.448760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e65fe66c865'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_date'), 'image', ['date'], unique=True)
    op.create_index(op.f('ix_image_filename'), 'image', ['filename'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('res_x', sa.Integer(), nullable=True),
    sa.Column('res_y', sa.Integer(), nullable=True),
    sa.Column('rotation', sa.Integer(), nullable=True),
    sa.Column('effect', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_effect'), 'settings', ['effect'], unique=False)
    op.create_index(op.f('ix_settings_res_x'), 'settings', ['res_x'], unique=False)
    op.create_index(op.f('ix_settings_res_y'), 'settings', ['res_y'], unique=False)
    op.create_index(op.f('ix_settings_rotation'), 'settings', ['rotation'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_rotation'), table_name='settings')
    op.drop_index(op.f('ix_settings_res_y'), table_name='settings')
    op.drop_index(op.f('ix_settings_res_x'), table_name='settings')
    op.drop_index(op.f('ix_settings_effect'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_image_filename'), table_name='image')
    op.drop_index(op.f('ix_image_date'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
