"""image table

Revision ID: a44fbfcd360b
Revises: 
Create Date: 2020-05-21 15:51:10.035620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44fbfcd360b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_date'), 'image', ['date'], unique=True)
    op.create_index(op.f('ix_image_filename'), 'image', ['filename'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_filename'), table_name='image')
    op.drop_index(op.f('ix_image_date'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
